### ISSUE TITLE
Tests not passing on Travis

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-pdfview#1]
They will once ckan/ckan#2270 is merged to master

**Comment by jqnatividad** [comment]
Strange.  The tests passed when I [created the PR](https://travis-ci.org/ckan/ckanext-pdfview/builds/54455235), but didn't [after the merge](https://travis-ci.org/ckan/ckanext-pdfview/builds/54718870).

https://travis-ci.org/ckan/ckanext-pdfview

**Comment by amercader** [comment]
@jqnatividad The current breakage is most likely caused by this being merged in master ckan/ckan#2221 and this import not working any more as expected

https://github.com/ckan/ckanext-pdfview/blob/master/ckanext/pdfview/tests/test_view.py#L6
https://github.com/ckan/ckanext-pdfview/blob/master/ckanext/pdfview/tests/test_view.py#L30
