### ISSUE TITLE
KeyError: 'ckanext' when install with pip

### ISSUE THREAD

**Issue by winggundamth** [ckan/ckanext-pdfview#17]
when I tried to install ckanext-pdfview with one of these commands

``` bash
pip install ckanext-pdfview
pip install git+https://github.com/ckan/ckanext-pdfview.git
```

It will always show this error after it done installed

```
Error processing line 2 of /usr/local/lib/python2.7/dist-packages/ckan-2.3-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'ckanext'

Remainder of file ignored
```

But if I install with these commands

``` bash
git clone https://github.com/ckan/ckanext-pdfview.git
cd ckanext-pdfview
python setup.py develop
```

It will work fine but ckan doesn't recognize pdf_view as plugin and show not found error.

**Comment by jqnatividad** [comment]
If you upgraded your installation to CKAN 2.3, please confirm that the old, bundled pdfview is removed.

`rm -rf  /usr/lib/ckan/default/src/ckan/ckanext/pdfview`

and then do a development installation and restart your webserver.

If it works, please confirm.  I'll need to update the README to recommend a development installation until the PyPI version is updated properly.

**Comment by winggundamth** [comment]
This is new installation of ckan 2.3. So only ckan 2.3 has been installed before I'm doing install pdfview extension.

**Comment by winggundamth** [comment]
For detail. This is how we install CKAN 2.3. Every other extensions work like charm except pdfview

``` bash
pip install ckan
pip install -r https://raw.githubusercontent.com/ckan/ckan/ckan-2.3/requirements.txt
pip install ckanext-pdfview
# Error happens
```

**Comment by jqnatividad** [comment]
Please do this:

```
. /usr/lib/ckan/default/bin/activate
cd /usr/lib/ckan/default/src
git clone https://github.com/ckan/ckanext-pdfview.git
cd ckanext-pdfview
python setup.py develop
sudo service apache2 reload
```

and let me know if you're still having problems

**Comment by winggundamth** [comment]
Thanks for reply but we're sorry. We deployed with difference way without apache. We're using uwsgi+nginx inside Docker container. So we didn't use virtualenv to deploy but deploy on global environment.

Are you saying that we should doing install latest code from pdfview repository instead of using pip install ckanext-pdfview?

**Comment by jqnatividad** [comment]
Yes.  Please install the latest code from the repo instead of using pip install.

**Comment by acorbi** [comment]
@winggundamth I could reproduce the Issue as you described and can confirm that installing the extension as @jqnatividad indicates works.

@jqnatividad The **develop** word in  `python setup.py develop` might confuse people thinking that that way of activating plugins is not production oriented, only for developing. Any possibility of renaming that comand in future releases?

**Comment by winggundamth** [comment]
@jqnatividad I tried to doing this. but CKAN didn't recognize pdf_view as ckan plugin

``` bash
pip install ckan
pip install -r https://raw.githubusercontent.com/ckan/ckan/ckan-2.3/requirements.txt
git clone https://github.com/ckan/ckanext-pdfview.git
cd ckanext-pdfview
python setup.py develop

paster make-config ckan /etc/ckan/production.ini
# Add pdf_view to ckan.plugins and ckan.views.default_views

paster --plugin=ckan db init --config=/etc/ckan/production.ini

Traceback (most recent call last):
  File "/usr/local/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/local/lib/python2.7/dist-packages/ckan/lib/cli.py", line 208, in command
    self._load_config(cmd!='upgrade')
  File "/usr/local/lib/python2.7/dist-packages/ckan/lib/cli.py", line 148, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/usr/local/lib/python2.7/dist-packages/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/usr/local/lib/python2.7/dist-packages/ckan/plugins/core.py", line 148, in load
    service = _get_service(plugin)
  File "/usr/local/lib/python2.7/dist-packages/ckan/plugins/core.py", line 255, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: pdf_view
```

**Comment by winggundamth** [comment]
@jqnatividad I think I've found the root cause of the problem
https://github.com/ckan/ckanext-pdfview/blob/master/ckanext/__init__.py
After I remove this file. The error disappear

I think __init__.py shouldn't be in ckanext/ folder. but it should be inside ckanext/extension_name folder

**Comment by jqnatividad** [comment]
Thanks @acorbi. @winggundamth, please see [#5](https://github.com/ckan/ckanext-pdfview/issues/5#issuecomment-93981833) and try doing a pip install again.

**Comment by winggundamth** [comment]
Tried both `pip install --upgrade ckanext-pdfview` and `pip install git+https://github.com/ckan/ckanext-pdfview.git#egg=ckanext-pdfview` but still got error

```
Error processing line 2 of /usr/local/lib/python2.7/dist-packages/ckan-2.3-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'ckanext'

Remainder of file ignored
```

**Comment by jqnatividad** [comment]
@winggundamth, are you still having an issue?

**Comment by jqnatividad** [comment]
Fixed in 0.0.4 release.  See #19.

**Comment by earthquakesan** [comment]
Hi!

I've created my own CKAN extension and had the same problem (installing using pip inside docker container). It can be solved by adding namespaces_packages to setup.py file.

Excerpt from setup.py should look like:

```
packages=find_packages(exclude=['contrib', 'docs', 'tests*']),
namespace_packages=['ckanext', 'ckanext.pdfview'],
```

If you take a look at setup.py of ckan-harvest extension they've got this line there: https://github.com/ckan/ckanext-harvest/blob/master/setup.py

**Comment by wardi** [comment]
I've run into the same thing https://github.com/earthquakesan/ckanext-pdfview/commit/ceae3d59cd43cb0d9c8da3d8393269c2b702ae38 is almost the right fix, it should only include ckanext not ckanext.pdfview

**Comment by jqnatividad** [comment]
@earthquakesan @wardi implemented the fix and updated the package.  

Please confirm it works on your end.

Thanks for the tip!

**Comment by wardi** [comment]
@jqnatividad all better here. Thanks!

**Comment by crstn-aiw** [comment]
Hi, 
I encountered a similar error with this and tried what I have read here but it is still throwing me the error.
I have the latest ckan 2.9, python 3.8 on ubuntu 20.04 
Any ideas? thank you
=======================errror==========================
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 282, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: pdf_view
=======================errror==========================

> . /usr/lib/ckan/default/bin/activate
> cd /usr/lib/ckan/default/src
> git clone https://github.com/ckan/ckanext-pdfview.git
> cd ckanext-pdfview
> python setup.py develop
> sudo service apache2 reload
