### ISSUE TITLE
Not Installed images, locale and cmaps when  "pip install ckanext-pdfview"

### ISSUE THREAD

**Issue by kazuomatz** [ckan/ckanext-pdfview#19]
I installed ckanext-pdfview on CKAN2.3.

$ source /usr/lib/ckan/default/bin/activate
$ pip install ckanext-pdfview

But a preview of PDF collapsed.

The following archive doesn't seem to have enough files.
- https://pypi.python.org/packages/source/c/ckanext-pdfview/ckanext-pdfview-0.0.3.tar.gz

It does not contain the following files .

.ckanext/pdfview/theme/public/vendor/pdfjs/web/cmaps/*
.ckanext/pdfview/theme/public/vendor/pdfjs/web/images/*
.ckanext/pdfview/theme/public/vendor/pdfjs/web/locale/[locale]/*
.ckanext/pdfview/theme/public/img/ajaxload-circle.gif

**Comment by jqnatividad** [comment]
@kazuomatz please do a development installation for now:

```
 git clone https://github.com/ckan/ckanext-pdfview.git
 cd ckanext-pdfview
 python setup.py develop
```

**Comment by kazuomatz** [comment]
Thanks. I understand.

**Comment by amercader** [comment]
@jqnatividad sorry, I missed all these on the MANIFEST.in when I did 63e3bf2753. We either need to add all relevant extensions or include the whole public dir if that's possible. Do you have a pypi account so you can publish new versions?

@kazuomatz do you want to send a PR including these? You can test if they are included running `python setup.py sdist`. This will create the package on `./build`.

**Comment by jqnatividad** [comment]
Hi @amercader, my pypi username is jqnatividad as well.

**Comment by amercader** [comment]
@jqnatividad Done

**Comment by kazuomatz** [comment]
@amercader No , it's OK. Thanks for your support.
