### ISSUE TITLE
BUG: AttributeError: 'module' object has no attribute 'ckanext-pdfview/main'

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-pdfview#3]
Version: 0.0.1 installed from pypi

`r = getattr(fanstatic_resources, resource)` doesn't like string being passed before in  `{% resource 'ckanext-pdfview/main' %}`

![pdf_view_bug](https://cloud.githubusercontent.com/assets/849975/6636359/952f89f6-c96f-11e4-9355-c429fb0f2cdd.png)

**Comment by jqnatividad** [comment]
Please try the Development Installation for now (see #5)

**Comment by amercader** [comment]
See https://github.com/ckan/ckanext-pdfview/issues/5#issuecomment-93981833

**Comment by KrzysztofMadejski** [comment]
Thx, will check it soon.

**Comment by jqnatividad** [comment]
Fixed in 0.0.4 release.  See #19
