### ISSUE TITLE
Embed button doesn't work when pdf_view is enabled

### ISSUE THREAD

**Issue by bohdanbobrowski** [ckan/ckanext-pdfview#33]
On CKAN 2.8.3 when pdf_view is enabled "Embed" button is displayed without border and after you click on that button, dialog box seems to be unvisible (proper html could be found in DOM but styles are overwritten by pdf_view plugin).

**Comment by bohdanbobrowski** [comment]
I have fixed that issue, and proposed a fix in this pull request: [https://github.com/ckan/ckanext-pdfview/pull/34](https://github.com/ckan/ckanext-pdfview/pull/34)

**Comment by jcballesteros** [comment]
Thanks a lot @bohdanbobrowski
It works like a charm!!
